AllCops:
  Exclude:
    - 'tracks/**/*'
    - 'test/fixtures/**/*'
    - 'bin/*'
    - 'vendor/**/*'
Style/StringLiterals:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/TrailingComma:
  EnforcedStyleForMultiline: comma
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'v1/**/*'
    - 'v3/**/*'
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/FormatString:
  Enabled: true
  EnforcedStyle: percent
Lint/RescueException:
  Exclude:
    - 'v1/helpers/errors.rb'
Metrics/LineLength:
  Max: 80
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
Metrics/LineLength:
  Exclude:
    - 'test/**/*'
